package config

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	ProjectFileName      = ".wktree.yaml"
	DefaultTmuxMode      = "window"
	DefaultWorkspaceMode = "single"
	WorkspaceModeAll     = "all"
)

var unsafeEnvNameChars = regexp.MustCompile(`[^A-Za-z0-9]+`)

type Config struct {
	WorktreeDir   string      `yaml:"worktree_dir"`
	Tmux          Tmux        `yaml:"tmux"`
	WorkspaceMode string      `yaml:"workspace_mode"`
	Defaults      Defaults    `yaml:"defaults"`
	Workspaces    []Workspace `yaml:"workspaces"`
	// Files is a legacy alias for Defaults.Files.
	Files Files `yaml:"files"`
	// Hooks is a legacy top-level hook block. Prefer workspace hooks for new config.
	Hooks Hooks `yaml:"hooks"`
}

type Defaults struct {
	Files Files `yaml:"files"`
}

type Tmux struct {
	Mode        string `yaml:"mode"`
	SessionName string `yaml:"session_name"`
}

type Workspace struct {
	Name           string          `yaml:"name"`
	Repo           string          `yaml:"repo"`
	Panes          []PaneCommand   `yaml:"panes"`
	RandomizePorts []RandomizePort `yaml:"randomize_ports"`
	SetEnv         []SetEnv        `yaml:"set_env"`
	Open           []string        `yaml:"open"`
	// Commands is a legacy alias for Panes.
	Commands []PaneCommand `yaml:"commands"`
	Files    Files         `yaml:"files"`
	Hooks    Hooks         `yaml:"hooks"`
}

type RandomizePort struct {
	File string   `yaml:"file"`
	Vars []string `yaml:"vars"`
}

type SetEnv struct {
	File string            `yaml:"file"`
	Vars map[string]string `yaml:"vars"`
}

type PaneCommand struct {
	Command    string   `yaml:"command"`
	Commands   []string `yaml:"commands"`
	Split      string   `yaml:"split"`
	Focus      bool     `yaml:"focus"`
	Zoom       bool     `yaml:"zoom"`
	Size       string   `yaml:"size"`
	Percentage int      `yaml:"percentage"`
}

type Files struct {
	Copy    []string `yaml:"copy"`
	Symlink []string `yaml:"symlink"`
}

type Hooks struct {
	PostCreate []string `yaml:"post_create"`
}

func ProjectPath(projectDir string) string {
	return filepath.Join(projectDir, ProjectFileName)
}

func ProjectTemplate() string {
	return `# wktree project config
# Generated by wktree init.
# Cleanup needs no config; preview with: wktree cleanup --dry-run

# worktree_dir: ~/workspace/worktrees
# tmux:
#   mode: window
#   session_name: "${repo}/${branch}"
# workspace_mode: single

workspaces:
  - name: window_name
    repo: .
    # files:
    #   copy:
    #     - .env.local
    #   symlink:
    #     - .tool-versions
    # hooks:
    #   post_create:
    #     - pnpm install
    # randomize_ports:
    #   - file: .env.local
    #     vars:
    #       - PORT
    #       - APP_PORT
    # set_env:
    #   - file: .env.local
    #     vars:
    #       API_URL: "http://localhost:${window_name:.env.local:PORT}/api"
    # open:
    #   - "http://localhost:${window_name:.env.local:PORT}"
    # panes:
    #   - command: nvim
    #     focus: true
    #   - commands:
    #       - pnpm install
    #       - pnpm run dev
    #     split: horizontal

# defaults:
#   files:
#     copy:
#       - .env
#     symlink:
#       - AGENTS.override.md
`
}

func WriteProjectTemplate(projectDir string) (string, error) {
	configPath := ProjectPath(projectDir)
	file, err := os.OpenFile(configPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		if os.IsExist(err) {
			return "", fmt.Errorf("config already exists: %s", configPath)
		}
		return "", err
	}
	_, writeErr := file.WriteString(ProjectTemplate())
	closeErr := file.Close()
	if writeErr != nil {
		return "", writeErr
	}
	if closeErr != nil {
		return "", closeErr
	}
	return configPath, nil
}

func FindProjectPath(startDir string, repoRoot string) (string, bool, error) {
	current, err := filepath.Abs(startDir)
	if err != nil {
		return "", false, err
	}
	current = filepath.Clean(current)
	root, err := filepath.Abs(repoRoot)
	if err != nil {
		return "", false, err
	}
	root = filepath.Clean(root)
	relative, err := filepath.Rel(root, current)
	if err != nil {
		return "", false, err
	}
	if relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) || filepath.IsAbs(relative) {
		return "", false, fmt.Errorf("start directory must be inside git repo root: %s", startDir)
	}

	for {
		configPath := ProjectPath(current)
		if _, err := os.Stat(configPath); err == nil {
			return configPath, true, nil
		} else if !os.IsNotExist(err) {
			return "", false, err
		}
		if current == root {
			return ProjectPath(root), false, nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			return ProjectPath(root), false, nil
		}
		current = parent
	}
}

func LoadProject(repoRoot string, homeDir string) (Config, error) {
	return LoadProjectFile(ProjectPath(repoRoot), homeDir)
}

func LoadProjectFile(configPath string, homeDir string) (Config, error) {
	config, err := LoadFile(configPath, homeDir)
	if err != nil {
		return Config{}, err
	}
	if config.Tmux.Mode == "" {
		config.Tmux.Mode = DefaultTmuxMode
	}
	if config.WorkspaceMode == "" {
		config.WorkspaceMode = DefaultWorkspaceMode
	}
	return config, nil
}

func LoadFile(filePath string, homeDir string) (Config, error) {
	stat, err := os.Stat(filePath)
	if os.IsNotExist(err) {
		return Config{}, nil
	}
	if err != nil {
		return Config{}, err
	}
	if !stat.Mode().IsRegular() {
		return Config{}, fmt.Errorf("config path is not a file: %s", filePath)
	}

	source, err := os.ReadFile(filePath)
	if err != nil {
		return Config{}, err
	}
	if len(bytes.TrimSpace(source)) == 0 {
		return Config{}, nil
	}

	var node yaml.Node
	if err := yaml.Unmarshal(source, &node); err != nil {
		return Config{}, fmt.Errorf("invalid YAML in %s: %w", filePath, err)
	}
	if err := validateNode(&node, filePath); err != nil {
		return Config{}, err
	}

	var config Config
	decoder := yaml.NewDecoder(bytes.NewReader(source))
	decoder.KnownFields(true)
	if err := decoder.Decode(&config); err != nil {
		return Config{}, fmt.Errorf("invalid config in %s: %w", filePath, err)
	}
	if err := validateConfig(&config, filePath, homeDir); err != nil {
		return Config{}, err
	}
	return config, nil
}

func (config Config) HasSetup() bool {
	if hasFiles(config.Defaults.Files) || hasFiles(config.Files) || hasHooks(config.Hooks) {
		return true
	}
	for _, workspace := range config.Workspaces {
		if hasFiles(workspace.Files) || hasHooks(workspace.Hooks) || len(workspace.RandomizePorts) > 0 || len(workspace.SetEnv) > 0 {
			return true
		}
	}
	return false
}

func WorkspaceFiles(config Config, workspace Workspace) Files {
	defaults := configDefaultsFiles(config)
	return Files{
		Copy:    append(append([]string(nil), defaults.Copy...), workspace.Files.Copy...),
		Symlink: append(append([]string(nil), defaults.Symlink...), workspace.Files.Symlink...),
	}
}

func WorkspaceHooks(config Config, workspace Workspace) Hooks {
	return Hooks{PostCreate: append(append([]string(nil), config.Hooks.PostCreate...), workspace.Hooks.PostCreate...)}
}

func WorkspacePanes(workspace Workspace) []PaneCommand {
	if len(workspace.Panes) > 0 {
		return workspace.Panes
	}
	return workspace.Commands
}

func validateConfig(config *Config, filePath string, homeDir string) error {
	if config.Tmux.Mode == "" {
		config.Tmux.Mode = DefaultTmuxMode
	}
	if config.Tmux.Mode != "window" && config.Tmux.Mode != "session" {
		return fmt.Errorf("invalid config in %s: tmux.mode must be \"window\" or \"session\"", filePath)
	}
	if config.WorkspaceMode == "" {
		config.WorkspaceMode = DefaultWorkspaceMode
	}
	if config.WorkspaceMode != "single" && config.WorkspaceMode != WorkspaceModeAll {
		return fmt.Errorf("invalid config in %s: workspace_mode must be \"single\" or \"all\"", filePath)
	}
	if config.WorktreeDir != "" {
		if _, err := expandPath(config.WorktreeDir, homeDir, filepath.Dir(filePath)); err != nil {
			return fmt.Errorf("invalid config in %s: worktree_dir %w", filePath, err)
		}
	}
	if err := validateTmuxSessionName(config.Tmux.SessionName); err != nil {
		return fmt.Errorf("invalid config in %s: tmux.session_name %w", filePath, err)
	}
	if hasFiles(config.Defaults.Files) && hasFiles(config.Files) {
		return fmt.Errorf("invalid config in %s: use defaults.files or files, not both", filePath)
	}
	if err := validateFiles(config.Defaults.Files, "defaults.files", filePath); err != nil {
		return err
	}
	if err := validateFiles(config.Files, "files", filePath); err != nil {
		return err
	}
	if err := validateStrings(config.Hooks.PostCreate, "hooks.post_create", filePath); err != nil {
		return err
	}

	names := map[string]bool{}
	envKeys := map[string]string{}
	for index, workspace := range config.Workspaces {
		prefix := fmt.Sprintf("workspaces[%d]", index)
		if strings.TrimSpace(workspace.Name) == "" {
			return fmt.Errorf("invalid config in %s: %s.name must be a non-empty string", filePath, prefix)
		}
		if names[workspace.Name] {
			return fmt.Errorf("invalid config in %s: duplicate workspace name %q", filePath, workspace.Name)
		}
		names[workspace.Name] = true
		envKey, err := WorkspaceDirEnvKey(workspace.Name)
		if err != nil {
			return fmt.Errorf("invalid config in %s: %s.name %w", filePath, prefix, err)
		}
		if previous, ok := envKeys[envKey]; ok {
			return fmt.Errorf("invalid config in %s: workspace env var %s conflicts between %q and %q", filePath, envKey, previous, workspace.Name)
		}
		envKeys[envKey] = workspace.Name
		if workspace.Repo != "" {
			if _, err := expandPath(workspace.Repo, homeDir, filepath.Dir(filePath)); err != nil {
				return fmt.Errorf("invalid config in %s: %s.repo %w", filePath, prefix, err)
			}
		}
		if err := validateFiles(workspace.Files, prefix+".files", filePath); err != nil {
			return err
		}
		if err := validateStrings(workspace.Hooks.PostCreate, prefix+".hooks.post_create", filePath); err != nil {
			return err
		}
		if err := validateRandomizePorts(workspace.RandomizePorts, prefix+".randomize_ports", filePath); err != nil {
			return err
		}
		if err := validateSetEnv(workspace.SetEnv, prefix+".set_env", filePath); err != nil {
			return err
		}
		if err := validateStrings(workspace.Open, prefix+".open", filePath); err != nil {
			return err
		}
		if len(workspace.Panes) > 0 && len(workspace.Commands) > 0 {
			return fmt.Errorf("invalid config in %s: %s must use panes or commands, not both", filePath, prefix)
		}
		paneLabel := prefix + ".panes"
		if len(workspace.Commands) > 0 {
			paneLabel = prefix + ".commands"
		}
		for paneIndex, pane := range WorkspacePanes(workspace) {
			if err := validatePaneCommand(pane, fmt.Sprintf("%s[%d]", paneLabel, paneIndex), filePath); err != nil {
				return err
			}
		}
	}
	return nil
}

func WorkspaceDirEnvKey(workspaceName string) (string, error) {
	name := unsafeEnvNameChars.ReplaceAllString(strings.ToUpper(workspaceName), "_")
	name = strings.Trim(name, "_")
	if name == "" {
		return "", fmt.Errorf("must contain at least one letter or digit for its .wktree.env variable")
	}
	return "WKTREE_" + name + "_DIR", nil
}

func validatePaneCommand(command PaneCommand, label string, filePath string) error {
	hasCommand := strings.TrimSpace(command.Command) != ""
	hasCommands := len(command.Commands) > 0
	switch {
	case hasCommand && hasCommands:
		return fmt.Errorf("invalid config in %s: %s must use command or commands, not both", filePath, label)
	case !hasCommand && !hasCommands:
		return fmt.Errorf("invalid config in %s: %s must define command or commands", filePath, label)
	}
	if command.Command != "" && strings.TrimSpace(command.Command) == "" {
		return fmt.Errorf("invalid config in %s: %s.command must be a non-empty string", filePath, label)
	}
	if err := validateStrings(command.Commands, label+".commands", filePath); err != nil {
		return err
	}
	if command.Split != "" && command.Split != "horizontal" && command.Split != "vertical" {
		return fmt.Errorf("invalid config in %s: %s.split must be \"horizontal\" or \"vertical\"", filePath, label)
	}
	if command.Percentage < 0 || command.Percentage > 100 {
		return fmt.Errorf("invalid config in %s: %s.percentage must be between 1 and 100", filePath, label)
	}
	return nil
}

func validateTmuxSessionName(template string) error {
	remaining := template
	for {
		start := strings.Index(remaining, "${")
		if start < 0 {
			return nil
		}
		afterStart := remaining[start+2:]
		end := strings.Index(afterStart, "}")
		if end < 0 {
			return fmt.Errorf("has unterminated template reference")
		}
		reference := afterStart[:end]
		if !isTmuxSessionNameReference(reference) {
			return fmt.Errorf("uses unknown template reference %q", reference)
		}
		remaining = afterStart[end+1:]
	}
}

func isTmuxSessionNameReference(reference string) bool {
	if reference == "repo" || reference == "branch" || reference == "dir" {
		return true
	}
	if !strings.HasPrefix(reference, "dir:") {
		return false
	}
	index := strings.TrimPrefix(reference, "dir:")
	if index == "" {
		return false
	}
	for _, char := range index {
		if char < '0' || char > '9' {
			return false
		}
	}
	return true
}

func validateFiles(files Files, label string, filePath string) error {
	if err := validateSetupPaths(files.Copy, label+".copy", filePath); err != nil {
		return err
	}
	return validateSetupPaths(files.Symlink, label+".symlink", filePath)
}

func validateRandomizePorts(randomizePorts []RandomizePort, key string, filePath string) error {
	for index, item := range randomizePorts {
		label := fmt.Sprintf("%s[%d]", key, index)
		if strings.TrimSpace(item.File) == "" {
			return fmt.Errorf("invalid config in %s: %s.file must be a non-empty string", filePath, label)
		}
		if err := validateSetupPaths([]string{item.File}, label+".file", filePath); err != nil {
			return err
		}
		if len(item.Vars) == 0 {
			return fmt.Errorf("invalid config in %s: %s.vars must define at least one variable", filePath, label)
		}
		seen := map[string]bool{}
		for varIndex, name := range item.Vars {
			varLabel := fmt.Sprintf("%s.vars[%d]", label, varIndex)
			if !isEnvVarName(name) {
				return fmt.Errorf("invalid config in %s: %s must be a valid env var name", filePath, varLabel)
			}
			if seen[name] {
				return fmt.Errorf("invalid config in %s: duplicate randomize port var %q in %s", filePath, name, label)
			}
			seen[name] = true
		}
	}
	return nil
}

func validateSetEnv(setEnv []SetEnv, key string, filePath string) error {
	for index, item := range setEnv {
		label := fmt.Sprintf("%s[%d]", key, index)
		if strings.TrimSpace(item.File) == "" {
			return fmt.Errorf("invalid config in %s: %s.file must be a non-empty string", filePath, label)
		}
		if err := validateSetupPaths([]string{item.File}, label+".file", filePath); err != nil {
			return err
		}
		if len(item.Vars) == 0 {
			return fmt.Errorf("invalid config in %s: %s.vars must define at least one variable", filePath, label)
		}
		for name := range item.Vars {
			if !isEnvVarName(name) {
				return fmt.Errorf("invalid config in %s: %s.vars key %q must be a valid env var name", filePath, label, name)
			}
		}
	}
	return nil
}

func isEnvVarName(value string) bool {
	if value == "" {
		return false
	}
	for index, char := range value {
		if index == 0 {
			if (char < 'A' || char > 'Z') && (char < 'a' || char > 'z') && char != '_' {
				return false
			}
			continue
		}
		if (char < 'A' || char > 'Z') && (char < 'a' || char > 'z') && (char < '0' || char > '9') && char != '_' {
			return false
		}
	}
	return true
}

func validateSetupPaths(values []string, key string, filePath string) error {
	if err := validateStrings(values, key, filePath); err != nil {
		return err
	}
	for index, value := range values {
		if filepath.IsAbs(value) {
			return fmt.Errorf("invalid config in %s: %s[%d] must be a relative file path", filePath, key, index)
		}
		if strings.ContainsRune(value, '\x00') {
			return fmt.Errorf("invalid config in %s: %s[%d] cannot contain null bytes", filePath, key, index)
		}
		for _, segment := range strings.FieldsFunc(value, func(r rune) bool { return r == '/' || r == '\\' }) {
			if segment == ".." {
				return fmt.Errorf("invalid config in %s: %s[%d] cannot contain \"..\"", filePath, key, index)
			}
		}
	}
	return nil
}

func validateStrings(values []string, key string, filePath string) error {
	for index, value := range values {
		if strings.TrimSpace(value) == "" {
			return fmt.Errorf("invalid config in %s: %s[%d] must be a non-empty string", filePath, key, index)
		}
	}
	return nil
}

func validateNode(node *yaml.Node, filePath string) error {
	if node.Kind == yaml.DocumentNode && len(node.Content) == 1 {
		node = node.Content[0]
	}
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("invalid config in %s: expected an object", filePath)
	}
	for i := 0; i < len(node.Content); i += 2 {
		key := node.Content[i].Value
		switch key {
		case "worktree_dir", "tmux", "workspace_mode", "defaults", "workspaces", "files", "hooks":
			if key == "tmux" {
				if err := validateTmuxNode(node.Content[i+1], filePath); err != nil {
					return err
				}
			}
			if key == "defaults" {
				if err := validateDefaultsNode(node.Content[i+1], filePath); err != nil {
					return err
				}
			}
		case "copy", "symlink", "postSetup", "windows", "mode", "tmux_mode", "tmux_session_name", "default_workspaces":
			return fmt.Errorf("invalid config in %s: legacy key %q is not supported", filePath, key)
		default:
			return fmt.Errorf("invalid config in %s: unsupported key %q", filePath, key)
		}
	}
	return nil
}

func validateDefaultsNode(node *yaml.Node, filePath string) error {
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("invalid config in %s: defaults must be an object", filePath)
	}
	for i := 0; i < len(node.Content); i += 2 {
		key := node.Content[i].Value
		switch key {
		case "files":
		case "hooks":
			return fmt.Errorf("invalid config in %s: defaults.hooks is not supported; use workspaces[].hooks", filePath)
		default:
			return fmt.Errorf("invalid config in %s: unsupported defaults key %q", filePath, key)
		}
	}
	return nil
}

func validateTmuxNode(node *yaml.Node, filePath string) error {
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("invalid config in %s: tmux must be an object", filePath)
	}
	for i := 0; i < len(node.Content); i += 2 {
		key := node.Content[i].Value
		switch key {
		case "mode", "session_name":
		default:
			return fmt.Errorf("invalid config in %s: unsupported tmux key %q", filePath, key)
		}
	}
	return nil
}

func ExpandConfiguredPath(value string, homeDir string, baseDir string) (string, error) {
	return expandPath(value, homeDir, baseDir)
}

func configDefaultsFiles(config Config) Files {
	if hasFiles(config.Defaults.Files) {
		return config.Defaults.Files
	}
	return config.Files
}

func expandPath(value string, homeDir string, baseDir string) (string, error) {
	expanded := strings.TrimSpace(value)
	if strings.ContainsRune(expanded, '\x00') {
		return "", fmt.Errorf("cannot contain null bytes")
	}
	if expanded == "" {
		return "", fmt.Errorf("must be a non-empty path")
	}
	if expanded == "~" {
		expanded = homeDir
	} else if strings.HasPrefix(expanded, "~/") {
		expanded = filepath.Join(homeDir, expanded[2:])
	}
	if !filepath.IsAbs(expanded) {
		expanded = filepath.Join(baseDir, expanded)
	}
	return filepath.Abs(expanded)
}

func hasFiles(files Files) bool {
	return len(files.Copy) > 0 || len(files.Symlink) > 0
}

func hasHooks(hooks Hooks) bool {
	return len(hooks.PostCreate) > 0
}
